:::{table} Output files for the `soxs_mdark` recipe and their respective ESO PRO keywords.
:name: soxs_mdark_output
:widths: 15, 35, 10, 20, 10, 10

| Label | Content                                                      | Data Type  | PRO CATG | PRO TYPE | PRO TECH |
| ----- | :----------------------------------------------------------- | ---------- |---------- |---------- |---------- |
| `MDARK` | Master dark frame (frame containing typical dark-current flux accumulated over the exposure time of the input frames) | FITS image |  `DARK_<ARM>`         |   `REDUCED`        |  `IMAGE`       |  

:::





