:::{table} Output files for the `soxs_offset` recipe and their respective ESO PRO keywords.
:name: soxs_offset_output
:widths: 15, 35, 10, 20, 10, 10

| Label   | Content                                                                           | Data Type  | PRO CATG | PRO TYPE | PRO TECH |
| ------- | :-------------------------------------------------------------------------------- | ---------- |---------- |---------- |---------- |


:::






