

:::{table} Output files for the `soxs_mbias` recipe and their respective ESO PRO keywords.
:name: soxs_mbias_output
:widths: 15, 35, 10, 20, 10, 10

| Label   | Content                                                                           | Data Type  | PRO CATG | PRO TYPE | PRO TECH |
| ------- | :-------------------------------------------------------------------------------- | ---------- |---------- |---------- |---------- |
| `MBIAS` | Master bias frame (frame containing typical bias-voltage applied to the detector) | FITS image | `MASTER_BIAS_<ARM>`          |  `REDUCED`           |   `IMAGE`      |

:::



