:::{table} Output files for the `soxs_disp_solution` recipe and their respective ESO PRO keywords.
:name: soxs_disp_solution_output
:widths: 15, 35, 10, 20, 10, 10

| Label                    | Content                          | Data Type  | PRO CATG | PRO TYPE | PRO TECH |
| ------------------------ | :------------------------------- | ---------- |---------- |---------- |---------- |
| `DISP_MAP`               | first pass dispersion solution   | FITS Table |  `DISP_TAB_<ARM>`         |      `REDUCED`     |    `ECHELLE,PINHOLE`       |
| `DISP_MAP_LINES`         | dispersion solution fitted lines | FITS Table |  -        |   -        |     -      |
| `DISP_MAP_LINES_MISSING` | undetected arc lines             | FITS Table |  -         |  -         |    -       |
| `DISP_MAP_RES`           | dispersion solution QC plots     | PDF        |  -         |   -        |     -      |



:::




