:::{table} Output files for the `soxs_nod` recipe and their respective ESO PRO keywords. Some output file may not be generated depending on the user's pipeline settings.
:name: soxs_nod_output
:widths: 15, 35, 10, 20, 10, 10

| Label                     | Content                                      | Data Type | PRO CATG | PRO TYPE | PRO TECH |
| ------------------------- | -------------------------------------------- | --------- |---------- |---------- |---------- |
| `EXTRACTED_ORDERS_TABLE`    | Table of the extracted source in each order  | FITS      |           |           |           |
| `EXTRACTED_MERGED_ASCII`    | Ascii version of extracted source spectrum   | TXT       |     -       |    -       |     -      |
| `EXTRACTED_MERGED_TABLE`    | Table of the extracted, order-merged         | FITS      |           |           |           |
| `OBJECT_TRACE_RES`          | Residuals of the object trace polynomial fit | PDF       |     -       |    -       |     -      |
| `BKGROUND`                  | Fitted intra-order image background          | PDF       |     -       |    -       |     -      |
| `EXTRACTED_ORDERS_QC_PLOT`  | QC plot of extracted source                  | PDF       |     -       |    -       |     -      |
| `EXTRACTED_MERGED_QC_PLOT`  | QC plot of extracted order-merged source     | PDF       |     -       |    -       |     -      |

:::




