:::{table} Output files for the `soxs_order_centres` recipe and their respective ESO PRO keywords.
:name: soxs_order_centres_output
:widths: 15, 35, 10, 20, 10, 10

| Label               | Content                                      | Data Type | PRO CATG | PRO TYPE | PRO TECH |
| ------------------- | :------------------------------------------- | --------- |---------- |---------- |---------- |
| `ORDER CENTRES`     | Polynomial fits to the order centre traces                      | FITS      |    `ORDER_TAB_<ARM>`       |     `REDUCED`      |    `ECHELLE,SLIT`       |
| `ORDER CENTRES RES` | Residuals of the order centre polynomial fit | PDF       |    -       |    -       |     -      |


:::





