:::{table} Ancillary (static) files required by the `soxs_nod` recipe. These files are packaged with and shipped with the code.
:name: table_soxs_nod_static
:widths: 40, 60

| Data Type | Content |
|:----|:----|
| FITS images | Default bad-pixel map |
| FITS Binary Table | A spectral format table for the detector, giving the minimum and maximum wavelengths covered by each spectral order. |


:::

