:::{table} Ancillary (static) files required by the `soxs_spatial_solution` recipe. These files are packaged with and shipped with the code.
:name: table_soxs_spatial_solution_static
:widths: 40, 60

| Data Type | Content |
|:----|:----|
| FITS images | Default bad-pixel map |
| FITS Binary Table | A spectral format table for the detector, giving the minimum and maximum wavelengths covered by each spectral order. |
| FITS Binary Table | An arc-lamp line list. This table gives the predicted x, y pixel position that each arc line is expected to appear near for each spectral order and pinhole in the multi-pinhole mask. |

:::
