:::{table} Quality Control metrics calculated in the `soxs_mflat` recipe.
:name: soxs_mflat_qc

| Label                | Description                                           | Unit      |
| -------------------- | ----------------------------------------------------- | --------- |
| `FRAC BAD PIXELS`      | Fraction of bad pixels                                |           |
| `INNER ORDER PIX MEAN` | Mean inner-order pixel value                     | electrons |
| `INNER ORDER PIX SUM`  | Sum of all inner-order pixel values              | electrons |
| `N BAD PIXELS `        | Number of bad pixels                                  |           |
| `NLOWSENS`             | Number of low-sensitivity pixels found in master flat | pixels    |
| `ORDEXP10`             | 10th percentile inter-order flux                 | electrons |
| `ORDEXP50`             | 50th percentile inter-order flux                 | electrons |
| `ORDEXP90`             | 90th percentile inter-order flux                 | electrons |
| `XRESMAX`              | Maximum residual in order edge fit along x-axis  | pixels    |
| `XRESMIN`              | Minimum residual in order edge fit along x-axis  | pixels    |
| `XRESRMS`              | Std-dev of residual order edge fit along x-axis  | pixels    |


:::

