:::{table} Quality Control metrics calculated in the `soxs_nod` recipe.
:name: soxs_nod_qc

| Label                | Description                                                | Unit      |
| -------------------- | ---------------------------------------------------------- | --------- |
| CSAMP                | Number of continuum sample clipped during solution fitting |           |
| FRAC BAD PIXELS      | Fraction of bad pixels                                     |           |
| INNER ORDER PIX MEAN | Mean inner-order pixel value                          | electrons |
| INNER ORDER PIX SUM  | Sum of all inner-order pixel values                   | electrons |
| N BAD PIXELS         | Number of bad pixels                                       |           |
| NORDERS              | Number of orders containing an object trace                |           |
| NSAMP                | Number of samples where a continuum is detected            |           |
| PSAMP                | Proportion of samples where a continuum is detected        |           |
| TSAMP                | Total number of samples along orders                       |           |
| XRESMAX              | Maximum residual in continuum fit along x-axis        | px        |
| XRESMIN              | Minimum residual in continuum fit along x-axis        | px        |
| XRESRMS              | Std-dev of residual continuum fit along x-axis        | px        |


:::

