:::{table} Quality Control metrics calculated in the `soxs_mbias` recipe.
:name: table_soxs_mbias_qc

| Label | Description | Unit |
| :------------ | :----------- | ------------- |
| `BADPIX FRAC` |                Fraction of bad pixels |   -       | 
| `MBIAS MEDIAN` | Median flux level of master bias |electrons | 
| `BADPIX NUM` | Number of bad pixels |  -        | 
| `FPN FRACMAX` | Maximum periodic pattern noise ratio in raw bias frames | - |
| `RAW RON` | RON in single BIAS |electrons | 
| `MASTER RON` | Combined RON in MBIAS |electrons | 
| `STRUCTX` | Slope of BIAS in X direction | - |
| `STRUCTY` | Slope of BIAS in Y direction | - |



:::



