:::{table} Quality Control metrics calculated in the `soxs_nod` recipe.
:name: soxs_nod_qc

| Label                | Description                                                | Unit      |
| -------------------- | ---------------------------------------------------------- | --------- |
| BADPIX FRAC      | Fraction of bad pixels                                     |           |
| INNER ORDER PIX MEAN | Mean inner-order pixel value                          | electrons |
| INNER ORDER PIX SUM  | Sum of all inner-order pixel values                   | electrons |
| BADPIX NUM         | Number of bad pixels                                       |           |
| N ORDERS              | Number of orders containing an object trace                |           |
| SAMPLES DET NUM                | Number of samples where a continuum is detected            |           |
| SAMPLES DET FRAC                | Fraction of samples where a continuum is detected        |           |
| SAMPLES TOT NUM                | Total number of samples along orders                       |           |
| SAMPLES CLIP NUM                | Number of continuum sample clipped during solution fitting |           |
| SAMPLES CLIP FRAC                | Fraction of detected continuum samples clipped during solution fitting |           |
| X RES MAX              | Maximum residual in continuum fit along x-axis        | px        |
| X RES MIN              | Minimum residual in continuum fit along x-axis        | px        |
| X RES SD              | Std-dev of residual continuum fit along x-axis        | px        |


:::

