:::{table} Quality Control metrics calculated in the `soxs_mdark` recipe.
:name: soxs_mdark_qc

| Label             | Description            | Unit |
| :---------------- | :--------------------- | ---- |
| `HOTPIX FRAC` |                Fraction of hot pixels | -           |
| `MDARK MEDIAN` | Median flux level of master dark | electrons |
| `HOTPIX NUM` |                  Number of hot pixels | -           |

:::


