:::{table} Quality Control metrics calculated in the `soxs_mbias` recipe.
:name: table_soxs_mbias_qc

| Label | Description | Unit |
| :------------ | :----------- | ------------- |
| `FRAC BAD PIXELS` |                Fraction of bad pixels |   -       | 
| `MBIAS MEDIAN` | Median flux level of master bias |electrons | 
| `N BAD PIXELS` | Number of bad pixels |  -        | 
| `PPNMAX` | Maximum periodic pattern noise ratio in raw bias frames | - |
| `RON DETECTOR` | RON in single BIAS |electrons | 
| `RON MASTER` | Combined RON in MBIAS |electrons | 
| `STRUCTX` | Slope of BIAS in X direction | - |
| `STRUCTY` | Slope of BIAS in Y direction | - |



:::



