:::{table} Quality Control metrics calculated in the `soxs_mdark` recipe.
:name: soxs_mdark_qc

| Label             | Description            | Unit |
| :---------------- | :--------------------- | ---- |
| `BADPIX FRAC` |                Fraction of bad pixels | -           |
| `MDARK MEDIAN` | Median flux level of master dark | electrons |
| `BADPIX NUM` |                  Number of bad pixels | -           |

:::


