:::{table} Quality Control metrics calculated in the `soxs_mdark` recipe.
:name: soxs_mdark_qc

| Label             | Description            | Unit | Acceptable Range |
| :---------------- | :--------------------- | ---- | ----------------- |
| `HOTPIX FRAC` |                Fraction of hot pixels | -           | - |
| `MDARK MEDIAN` | Median flux level of master dark | electrons | NIR: [-15, 50] |
| `HOTPIX NUM` |                  Number of hot pixels | -           | - |
| `RAW RON` | RON in single DARK | electrons | NIR: [0,30] |

:::

==UPDATE QCs==
