:::{table} Quality Control metrics calculated in the `soxs_spatial_solution` recipe.
:name: soxs_spatial_solution_qc

| Label | Description                                                          | Unit  |
| :---- | :------------------------------------------------------------------- | ----- |
| DETLINES CLIP NUM | Total number of detected lines clipped during solution fitting       | lines |
| DETLINES NUM | Number of lines detected in single pinhole frame                     | lines |
| DETLINES FRAC | Proportion of input line-list lines detected on single pinhole frame |       |
| DETLINES TOT | Total number of line in single line-list                             | lines |

:::






