:::{table} Quality Control metrics calculated in the `soxs_order_centres` recipe.
:name: soxs_order_centres_qc

| Label   | Description                                                | Unit |
| ------- | ---------------------------------------------------------- | ---- |
| `N ORDERS` | Number of order centre traces found                        |      |
| `SAMPLES DET NUM`                | Number of samples where a continuum is detected            |           |
| `SAMPLES DET FRAC`                | Fraction of samples where a continuum is detected        |           |
| `SAMPLES TOT NUM`                | Total number of samples along orders                       |           |
| `SAMPLES CLIP NUM`                | Number of continuum sample clipped during solution fitting |           |
| `SAMPLES CLIP FRAC `               | Fraction of detected continuum samples clipped during solution fitting |           |
| `X RES MAX` | Maximum residual in order centre fit along x-axis     | px   |
| `X RES MIN` | Minimum residual in order centre fit along x-axis     | px   |
| `X RES SD` | Std-dev of residual order centre fit along x-axis     |      |
:::





