:::{table} Quality Control metrics calculated in the `soxs_stare` recipe.
:name: soxs_stare_qc

| Label                | Description                                                | Unit      |
| -------------------- | ---------------------------------------------------------- | --------- |
| SAMPLES NCLIP                | Number of continuum sample clipped during solution fitting |           |
| BADPIX FRAC      | Fraction of bad pixels                                     |           |
| INNER ORDER PIX MEAN | Mean inner-order pixel value                          | electrons |
| INNER ORDER PIX SUM  | Sum of all inner-order pixel values                   | electrons |
| BADPIX NUM         | Number of bad pixels                                       |           |
| NORDERS              | Number of orders containing an object trace                |           |
| SAMPLES NUM                | Number of samples where a continuum is detected            |           |
| SAMPLES FRAC                | Proportion of samples where a continuum is detected        |           |
| SAMPLES TOT                | Total number of samples along orders                       |           |
| X RES MAX              | Maximum residual in continuum fit along x-axis        | px        |
| X RES MIN              | Minimum residual in continuum fit along x-axis        | px        |
| X RES SD              | Std-dev of residual continuum fit along x-axis        | px        |



:::


