name: Integration Tests

on: [pull_request]


jobs:
  call-workflow:
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    uses: thespacedoctor/reusable-workflows/.github/workflows/integration-tests.yml@main
    with:
      python-version: ${{ matrix.python-version }}
